/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module scm_a (
    X,
    Y
);

  // Port mode declarations:
  input  signed  [15:0] X;
  output signed  [15:0] Y;

  //Multipliers:

  wire signed [28:0]
    w1,
    w4,
    w5,
    w160,
    w165,
    w5120,
    w4955,
    w40,
    w4915;

  assign w1 = X;
  assign w4 = w1 << 2;
  assign w5 = w1 + w4;
  assign w160 = w5 << 5;
  assign w165 = w5 + w160;
  assign w5120 = w5 << 10;
  assign w4955 = w5120 - w165;
  assign w40 = w5 << 3;
  assign w4915 = w4955 - w40;

  assign Y = w4915[28:13];

endmodule //multiplier_block

